/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyJourneyIdRouteImport } from './routes/journey/$journeyId'
import { Route as BookingNewRouteImport } from './routes/booking/new'
import { Route as BookingBookingCodeRouteImport } from './routes/booking/$bookingCode'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyJourneyIdRoute = JourneyJourneyIdRouteImport.update({
  id: '/journey/$journeyId',
  path: '/journey/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingNewRoute = BookingNewRouteImport.update({
  id: '/booking/new',
  path: '/booking/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingCodeRoute = BookingBookingCodeRouteImport.update({
  id: '/booking/$bookingCode',
  path: '/booking/$bookingCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/booking/new': typeof BookingNewRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/booking/new': typeof BookingNewRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/booking/new': typeof BookingNewRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/search'
    | '/booking/$bookingCode'
    | '/booking/new'
    | '/journey/$journeyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/booking/$bookingCode'
    | '/booking/new'
    | '/journey/$journeyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/search'
    | '/booking/$bookingCode'
    | '/booking/new'
    | '/journey/$journeyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  BookingBookingCodeRoute: typeof BookingBookingCodeRoute
  BookingNewRoute: typeof BookingNewRoute
  JourneyJourneyIdRoute: typeof JourneyJourneyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$journeyId': {
      id: '/journey/$journeyId'
      path: '/journey/$journeyId'
      fullPath: '/journey/$journeyId'
      preLoaderRoute: typeof JourneyJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/new': {
      id: '/booking/new'
      path: '/booking/new'
      fullPath: '/booking/new'
      preLoaderRoute: typeof BookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingCode': {
      id: '/booking/$bookingCode'
      path: '/booking/$bookingCode'
      fullPath: '/booking/$bookingCode'
      preLoaderRoute: typeof BookingBookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  BookingBookingCodeRoute: BookingBookingCodeRoute,
  BookingNewRoute: BookingNewRoute,
  JourneyJourneyIdRoute: JourneyJourneyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
