/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TouristiqueRouteImport } from './routes/touristique'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MessagerieRouteImport } from './routes/messagerie'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyJourneyIdRouteImport } from './routes/journey/$journeyId'
import { Route as BookingBookingCodeRouteImport } from './routes/booking/$bookingCode'
import { Route as BookingCheckoutJourneyIdRouteImport } from './routes/booking/checkout.$journeyId'

const TouristiqueRoute = TouristiqueRouteImport.update({
  id: '/touristique',
  path: '/touristique',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagerieRoute = MessagerieRouteImport.update({
  id: '/messagerie',
  path: '/messagerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyJourneyIdRoute = JourneyJourneyIdRouteImport.update({
  id: '/journey/$journeyId',
  path: '/journey/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBookingCodeRoute = BookingBookingCodeRouteImport.update({
  id: '/booking/$bookingCode',
  path: '/booking/$bookingCode',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCheckoutJourneyIdRoute =
  BookingCheckoutJourneyIdRouteImport.update({
    id: '/booking/checkout/$journeyId',
    path: '/booking/checkout/$journeyId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messagerie': typeof MessagerieRoute
  '/search': typeof SearchRoute
  '/touristique': typeof TouristiqueRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
  '/booking/checkout/$journeyId': typeof BookingCheckoutJourneyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messagerie': typeof MessagerieRoute
  '/search': typeof SearchRoute
  '/touristique': typeof TouristiqueRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
  '/booking/checkout/$journeyId': typeof BookingCheckoutJourneyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messagerie': typeof MessagerieRoute
  '/search': typeof SearchRoute
  '/touristique': typeof TouristiqueRoute
  '/booking/$bookingCode': typeof BookingBookingCodeRoute
  '/journey/$journeyId': typeof JourneyJourneyIdRoute
  '/booking/checkout/$journeyId': typeof BookingCheckoutJourneyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/messagerie'
    | '/search'
    | '/touristique'
    | '/booking/$bookingCode'
    | '/journey/$journeyId'
    | '/booking/checkout/$journeyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/messagerie'
    | '/search'
    | '/touristique'
    | '/booking/$bookingCode'
    | '/journey/$journeyId'
    | '/booking/checkout/$journeyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/messagerie'
    | '/search'
    | '/touristique'
    | '/booking/$bookingCode'
    | '/journey/$journeyId'
    | '/booking/checkout/$journeyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MessagerieRoute: typeof MessagerieRoute
  SearchRoute: typeof SearchRoute
  TouristiqueRoute: typeof TouristiqueRoute
  BookingBookingCodeRoute: typeof BookingBookingCodeRoute
  JourneyJourneyIdRoute: typeof JourneyJourneyIdRoute
  BookingCheckoutJourneyIdRoute: typeof BookingCheckoutJourneyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/touristique': {
      id: '/touristique'
      path: '/touristique'
      fullPath: '/touristique'
      preLoaderRoute: typeof TouristiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messagerie': {
      id: '/messagerie'
      path: '/messagerie'
      fullPath: '/messagerie'
      preLoaderRoute: typeof MessagerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$journeyId': {
      id: '/journey/$journeyId'
      path: '/journey/$journeyId'
      fullPath: '/journey/$journeyId'
      preLoaderRoute: typeof JourneyJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$bookingCode': {
      id: '/booking/$bookingCode'
      path: '/booking/$bookingCode'
      fullPath: '/booking/$bookingCode'
      preLoaderRoute: typeof BookingBookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/checkout/$journeyId': {
      id: '/booking/checkout/$journeyId'
      path: '/booking/checkout/$journeyId'
      fullPath: '/booking/checkout/$journeyId'
      preLoaderRoute: typeof BookingCheckoutJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MessagerieRoute: MessagerieRoute,
  SearchRoute: SearchRoute,
  TouristiqueRoute: TouristiqueRoute,
  BookingBookingCodeRoute: BookingBookingCodeRoute,
  JourneyJourneyIdRoute: JourneyJourneyIdRoute,
  BookingCheckoutJourneyIdRoute: BookingCheckoutJourneyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
